### ISSUE TITLE
change color of circle of route builder

### ISSUE THREAD

**Issue by boucoding** [tiamo/flutter-concentric-transition#1]
I am using this plugin to make the transition but it shows a black circle at the bottom 
how to make this invisible or transparent color

Thanks,

**Comment by Fethi-Hamdani** [comment]
same issue, it is appearing on top of the page and it is really bad which it can be transparent

**Comment by Lunari8546** [comment]
How to fix it?

**Comment by KattyNekoo** [comment]
Hello, I'm also using this and I discovered how to modify it.
First you have to download the original files, because if you import the package you wont be able to modify it internally.
[https://github.com/tiamo/flutter-concentric-transition/tree/master/lib]
There I found the ones I needed: clipper and page_route.

I modified on page_route: Line 109:
`return Container(
      child: ClipPath(
        clipper: ConcentricClipper(progress: _opacityAnimation.value, radius: 0.0 - 1.0),
        child: child,
      ),
    );`

If you see clipper file the radius works with pow, so if you put a negative radius the circle will disappear.
Also on line 28 you can change the colour of the transition.
I suggest to download the clipper because maybe you want to do some modification. Hope it helps.
Cya! ;3

**Comment by LucasG04** [comment]
Thanks @KattyNekoo 
I forked and changed it so it's easier to apply. Add this to your `pubspec.yaml`:
```yaml
  concentric_transition:
    git:
      url: https://github.com/LucasG04/flutter-concentric-transition.git
```

**Comment by Lunari8546** [comment]
@LucasG04 how about you make a pull request?
